general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. AVISO: Notificación en pantalla (4 min)
listener {
    timeout = 240                                
    on-timeout = notify-send "Inactividad detectada" "El equipo se bloqueará pronto..." -i system-lock-screen
}

# 2. BLOQUEO: Hyprlock (5 min)
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# 3. AHORRO: Apagar monitor (10 min)
listener {
    timeout = 600                                                     
    on-timeout = hyprctl dispatch dpms off                            
    on-resume = hyprctl dispatch dpms on
}

# 4. CIERRE: Suspensión total (15 min)
listener {
    timeout = 900
    on-timeout = systemctl suspend                
}

